version: 2.1

workflows:
  version: 2
  main:
    jobs:
      - test-code
      - test-docs

jobs:
  test-code:
    docker:
      - image: circleci/python:3.8
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: Create Virtualenv
          command: |
            virtualenv venv
      - run:
          name: Install Dependencies
          command: |
            . venv/bin/activate
            pip3 install -r requirements.txt
      # Step 3: run pylint styling check
      - run:
          name: Run Pylint Check
          command: |
            . venv/bin/activate
            pylint arbitragelab tests --rcfile=.pylintrc -f text
      # Step 4: run coverage check
      - run:
          name: Run Unit Tests and Coverage Check
          command: |
            bash coverage
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  test-docs:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            python 3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r docs/source/requirements.txt

      - run:
          name: Build documentation
          command: |
            . venv/bin/activate
            make -C docs html

      - run:
          name: Run doctests
          command: |
            . venv/bin/activate
            make -C docs doctest
